/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author UNKNOWN'PC
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        balmondLB = new javax.swing.JLabel();
        vexanaLB = new javax.swing.JLabel();
        nanaLB = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        balmondBT = new javax.swing.JButton();
        vexanaBT = new javax.swing.JButton();
        nanaBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Penampil Gambar Button");

        imagePanel.setAlignmentX(1.0F);
        imagePanel.setAlignmentY(1.0F);
        imagePanel.setLayout(new java.awt.CardLayout());

        balmondLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balmondLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/balmond.jpg"))); // NOI18N
        balmondLB.setToolTipText("null");
        balmondLB.setMinimumSize(new java.awt.Dimension(316, 400));
        balmondLB.setName("null"); // NOI18N
        balmondLB.setPreferredSize(new java.awt.Dimension(316, 400));
        balmondLB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imagePanel.add(balmondLB, "0");
        balmondLB.getAccessibleContext().setAccessibleName("0");

        vexanaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vexanaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/vexana.jpg"))); // NOI18N
        vexanaLB.setMaximumSize(new java.awt.Dimension(316, 400));
        vexanaLB.setMinimumSize(new java.awt.Dimension(316, 400));
        vexanaLB.setName("null"); // NOI18N
        vexanaLB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(vexanaLB, "1");
        vexanaLB.getAccessibleContext().setAccessibleName("1");

        nanaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nanaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nana.jpg"))); // NOI18N
        nanaLB.setToolTipText("null");
        nanaLB.setName("null"); // NOI18N
        imagePanel.add(nanaLB, "2");
        nanaLB.getAccessibleContext().setAccessibleName("2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        balmondBT.setText("balmond");
        balmondBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balmondBTActionPerformed(evt);
            }
        });
        buttonPanel.add(balmondBT);

        vexanaBT.setText("vexana");
        vexanaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vexanaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(vexanaBT);

        nanaBT.setText("nana");
        nanaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nanaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(nanaBT);

        exitBT.setText("Exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    private void nanaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nanaBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_nanaBTActionPerformed

    private void vexanaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vexanaBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_vexanaBTActionPerformed

    private void balmondBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balmondBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_balmondBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balmondBT;
    private javax.swing.JLabel balmondLB;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton nanaBT;
    private javax.swing.JLabel nanaLB;
    private javax.swing.JButton vexanaBT;
    private javax.swing.JLabel vexanaLB;
    // End of variables declaration//GEN-END:variables
}
